[package]
name = "advent-of-code"
version = "2.0.24"
authors = ["Robert Klink <roberthklink@gmail.com>"]
edition = "2021"

[lib]
name = "aoc"
path = "aoc/lib.rs"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
